In [1]:
import pandas as pd
import numpy as np

In [24]:
pd.Series?

In [13]:
#pandas series is a special numpy array
# Labels need not be unique but must be a hashable type. The object
# supports both integer- and label-based indexing and provides a host of
# methods for performing operations involving the index. Statistical
# methods from ndarray have been overridden to automatically exclude
# missing data (currently represented as NaN).
x=pd.Series(data=[1,2,3,4])
print("print x\n",x)
x.values

print x
 0    1
1    2
2    3
3    4
dtype: int64


array([1, 2, 3, 4], dtype=int64)

In [18]:
x=pd.Series(data=[1,2,3,4],index=["a","b","c","d"])
print("print x\n",x)
x=pd.Series(data=[1,2,3,4],index=[2,5,6,7])
print("print x\n",x)

print x
 a    1
b    2
c    3
d    4
dtype: int64
print x
 2    1
5    2
6    3
7    4
dtype: int64


In [26]:
d={"Qianghui":100,"Jack":99}
x=pd.Series(d)
print("print x\n",x)

print x
 Qianghui    100
Jack         99
dtype: int64


In [28]:
arr=np.array([1,2,3])
pd.Series(arr)

0    1
1    2
2    3
dtype: int32

# Several ways to Create a Pandas Series (pd.Series(data,index))
1. from numpy array 
2. from primitive python list 
3. from dict (key is taken as Series's index)

The Series index can be explicity specified , not constraint to the ordered index ,like [0,1,2]

In [32]:
pd.DataFrame?
# Two-dimensional size-mutable, potentially heterogeneous tabular data
# structure with labeled axes (rows and columns). Arithmetic operations
# align on both row and column labels. Can be thought of as a dict-like
# container for Series objects.

In [34]:
#DataFrame from dict-like container for Pd.Series
population_dict={"FuJian":100,"Hunan":110}
area_dict={"FuJian":1,"Hunan":2}
population=pd.Series(population_dict)
area=pd.Series(area_dict)
pd.DataFrame({"population":population,"area":area})
# the inserted series should share the same indexing. As to this case, the index is Index(["FuJian","Hunan"],dtype='object')

population  area
FuJian         100     1
Hunan          110     2

In [37]:
#DataFrame from dict-like container for python list
# data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
#     Dict can contain Series, arrays, constants, or list-like objects
population_list=[100,110]
area_list=[1,2]
pd.DataFrame({"population":population_list,"area":area_list})

population  area
0         100     1
1         110     2

In [40]:
# pd.DataFrame from numpy two-dimensional array
x=np.random.randint(0,10,size=(3,3))
pd.DataFrame(x,columns=["a","b","c"],index=[0,1,2])

a  b  c
0  8  1  6
1  0  6  5
2  0  4  7

In [7]:
#DataFrame from numpy structured matrox
type1=[("name",(np.str,10)),("age",np.int)]
x=np.ones(5,dtype=type1)
y=pd.DataFrame(x)
y

name  age
0    1    1
1    1    1
2    1    1
3    1    1
4    1    1

# Several ways to create a pandas DataFrame
Pd.DataFrame(data, columns, index)
1. From multiple pandas series by specifying the columns (These series should share the same index)
pd.DataFrame(s1,s2,columns=["s1","s2"])
2. Dict-like container for multiple series
pd.DataFrame({"s1":s1,"s2":s2})
3. Dict-like container for mutiple numpy array (1D) or primitive python list 
s1=np...
s2=np..
pd.DataFrame({"s1":s1,"s2":s2})

4. from 2D numpy array
pd.DataFrame(ss,columns=["s1","s2"],index=[0,1])
5. from numpy structured matirx

A=np.zeros(3,dtype=[("name",np.str),["age",np.int]])
pd.DataFrame(A)

#What is Pandas Index
Pandas Index Object is a immutable and ordered collections 

In [9]:
y.index

RangeIndex(start=0, stop=5, step=1)

In [14]:
i=pd.Index(["FuJian","HuNan","HaiNan"])
i

Index(['FuJian', 'HuNan', 'HaiNan'], dtype='object')

In [16]:
i[0]

'FuJian'

In [19]:
i[0:2]

Index(['FuJian', 'HuNan'], dtype='object')

In [22]:
i[1]="HeNan"

TypeError: Index does not support mutable operations

In [24]:
# the pd index is a ordered collection , like data structure SET, 
indA=pd.Index([1,2,3,4,5])
indB=pd.Index([9,2,3,4,8])
indA & indB #交集
indA | indB #并集
indA ^ indB #异或

Int64Index([1, 5, 8, 9], dtype='int64')

# Operations of Series


1.index (dict-like)
2. slice 

recommend use loc and iloc to index the Series values


In [26]:
data=pd.Series(np.arange(5),index=["a","b","c","d","e"])
data


a    0
b    1
c    2
d    3
e    4
dtype: int32

In [39]:
#dict-like index
print(data["a"])
print(data.keys())
print(data.values)
data.values?

0
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
[0 1 2 3 4]


In [43]:
#numpy-like operations 
print(data["a":"c"]) #slice

a    0
b    1
c    2
dtype: int32


In [45]:
data<2

a     True
b     True
c    False
d    False
e    False
dtype: bool

In [47]:
data[data<2] #bool index

a    0
b    1
dtype: int32

In [49]:
data[["b","c","a"]] #fancy index

b    1
c    2
a    0
dtype: int32

#Pay attentions to the Series Index
When you explicitly specify the Series Index as Integers , you then have two kinds of integer index, that is, the implicit ordered index and the explicit user-defined indexs. You should keep in mind which kind of index is used to one operation. The following is a trick example

In [52]:
x=pd.Series(data=["a","b","c"],index=[1,3,5])
x

1    a
3    b
5    c
dtype: object

In [55]:
x[1] # the simple index operation use the explict index 

'a'

In [57]:
x[1:3] # the slice index use the implicit index

3    b
5    c
dtype: object

# Recommend use loc and iloc to index the Pd Series and DataFrame
#Therefore, the pd Series introduced two method, loc and iloc
1. loc: use the explict index to locate the Series values
2. iloc: use the implicit index to locate the Series values



In [63]:
x.loc?

In [65]:
print(x.loc[1])
x.loc[1:3]

a


1    a
3    b
dtype: object

In [67]:
x.iloc?

In [74]:
print(x)
print(x.iloc[1]) #implicit index
print(x.loc[1]) #explicit index

1    a
3    b
5    c
dtype: object
b
a


In [77]:
print(x.iloc[1:3]) #implicit index
print(x.loc[1:3]) #explicit index 

3    b
5    c
dtype: object
1    a
3    b
dtype: object


In [79]:
# Operations of Pd DataFrame
# 1. dict-like
# 2. 2D array-like
area=pd.Series({"Hunan":1,"FuJian":2,"Henan":3})
population=pd.Series({"Hunan":11,"FuJian":21,"Henan":31})
df=pd.DataFrame({"area":area,"population":population})
df

area  population
Hunan      1          11
FuJian     2          21
Henan      3          31

In [82]:
print(type(df.area))
df.area #df is like a object , while area is like the object attribute
#however, this attribute-styple only support the string-like index
#when the index is not string, the attribute style indexing is invalid

<class 'pandas.core.series.Series'>


Hunan     1
FuJian    2
Henan     3
Name: area, dtype: int64

In [83]:
df["area"] # df is a dict-like container for the pd series=> dict-like operatioin


Hunan     1
FuJian    2
Henan     3
Name: area, dtype: int64

In [85]:
df["area"] is df.area

True

In [89]:
df.values #it is a 2D numpy array

array([[ 1, 11],
       [ 2, 21],
       [ 3, 31]], dtype=int64)

In [91]:
df.T

Hunan  FuJian  Henan
area            1       2      3
population     11      21     31

In [97]:
df.values[0:2]

array([[ 1, 11],
       [ 2, 21]], dtype=int64)

In [107]:
df.iloc[0:2]

area  population
Hunan      1          11
FuJian     2          21

In [109]:
df.iloc[0:2,:]

area  population
Hunan      1          11
FuJian     2          21

In [110]:
df.iloc[:2,:1]

area
Hunan      1
FuJian     2

In [101]:
df.loc[["Hunan","Henan"]]

area  population
Hunan     1          11
Henan     3          31

In [103]:
df.loc[["Henan","Hunan"],["area"]]

area
Henan     3
Hunan     1

In [111]:
df.loc["Hunan":"Henan",["area"]]

area
Hunan      1
FuJian     2
Henan      3

In [113]:
df["density"]=df["area"]/df["population"]
df

area  population   density
Hunan      1          11  0.090909
FuJian     2          21  0.095238
Henan      3          31  0.096774

In [115]:
df.loc[df.density>0.091]

area  population   density
FuJian     2          21  0.095238
Henan      3          31  0.096774

In [118]:
df.loc[df.density>0.091,["area","density"]]

area   density
FuJian     2  0.095238
Henan      3  0.096774