In [2]:
import numpy as np
np.__version__

'1.16.4'

# numpy [] operations can be : 
1. simple index like x[2], 
2. slice like x[::2],
3. bool index like x[np.array([false,true])],
4. fancy indexing x[np.array([1,2,3])]
5. combined indexing 

In [5]:
L=[1,2,3]
np.array(L)

array([1, 2, 3])

In [33]:
x=np.arange(10)
x.shape

(10,)

In [22]:
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
x[:2,:2]

array([[1, 2],
       [5, 6]])

In [24]:
x[:,0]

array([1, 5, 9])

In [26]:
x[0,:]

array([1, 2, 3, 4])

In [3]:
x=np.array([1,2,3])
x.shape

(3,)

In [5]:
x.reshape([1,3])

array([[1, 2, 3]])

In [6]:
x[np.newaxis,:]

array([[1, 2, 3]])

In [7]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [30]:
x.reshape([3,1])

array([[1],
       [2],
       [3]])

In [37]:
y=np.array([1,2,3])
y.shape  

(3,)

In [15]:
x=np.arange(1,10).reshape(3,3)
x[:2,:2][0,0]=10
x

array([[10,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [23]:
y=x[:2,:2].copy()
y[:2,:2]=1
x

array([[10,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
y=x[:2,:2].copy

In [40]:
y[np.newaxis,:].shape

(1, 3)

In [42]:
y[:,np.newaxis].shape

(3, 1)

In [46]:
X=np.random.random((10,3))
X

array([[0.74812438, 0.84476166, 0.60021044],
       [0.77222626, 0.88061101, 0.68615053],
       [0.46525226, 0.33575909, 0.58389986],
       [0.23017667, 0.09913987, 0.40419948],
       [0.83642421, 0.01499095, 0.5377017 ],
       [0.53737733, 0.16576673, 0.66000256],
       [0.12064627, 0.25372534, 0.99955008],
       [0.36432717, 0.69211213, 0.54553138],
       [0.68248839, 0.86516493, 0.33896914],
       [0.79658311, 0.0501268 , 0.272648  ]])

In [32]:
np.random?

In [36]:
X=np.random.normal(0,1,(2,2))
X

array([[ 0.90329369,  0.11176696],
       [-0.81412094,  0.5563138 ]])

In [40]:
X.var()

0.4143377683990467

In [43]:
y=np.arange(0,9).reshape(3,3)
2**y

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [49]:
np.add(y,1)
np.subtract(y,1)
np.negative(y)
np.multiply(y,2)
np.mod(y,2)

array([[0, 1, 0],
       [1, 0, 1],
       [0, 1, 0]], dtype=int32)

In [56]:
theta=np.linspace(0.0,np.pi,3)
print(theta)
np.sin(theta)

[0.         1.57079633 3.14159265]


array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [61]:
x=[1,2,3]
y=np.log(x)
np.exp(x)
np.exp2(x)
np.power(10,x)

array([  10,  100, 1000], dtype=int32)

In [65]:
x=np.arange(1,6,dtype=np.int)
y=np.empty(5)
np.multiply(x,2,out=y)
y

array([ 2.,  4.,  6.,  8., 10.])

In [66]:
##reduce function
x=np.arange(0,5)
np.add.reduce(x)

10

In [68]:
np.multiply.reduce(x)

0

In [70]:
#accumulate function
np.add.accumulate(x)

array([ 0,  1,  3,  6, 10], dtype=int32)

In [76]:
#sum 
np.random.seed(0)
x=np.random.random(100)
%timeit sum(x)
%timeit np.sum(x)

42.4 µs ± 656 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
7.74 µs ± 206 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [81]:
#np.argmin
x=np.random.randint(0,10,size=(3,3))
print(x)
np.argmin(x)

[[1 8 0]
 [4 9 6]
 [5 7 8]]


2

In [89]:
#percentile
x=np.random.normal(0,1,size=(11,))
print(np.sort(x))
print(np.mean(x))
np.percentile(x,50)

[-0.77963481 -0.6017086  -0.5471638  -0.35859784 -0.03636653  0.47633669
  0.58891422  0.70592839  0.73198245  0.83388012  1.31379269]
0.21157845245275908


0.47633669040961846

In [90]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn;seaborn.set()
plt.hist(x)

ModuleNotFoundError: No module named 'matplotlib'

In [52]:
Xmean=np.mean(X,axis=0)

In [55]:
Xcenter=X-Xmean

In [59]:
np.mean(Xcenter,axis=0)

array([-6.66133815e-17, -1.66533454e-17,  5.55111512e-17])

In [94]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.add(a,b)
a+b
a+5

array([6, 7, 8])

In [62]:
x=np.array([1,2,3,4,5])

In [64]:
x<3

array([ True,  True, False, False, False])

In [65]:
x>3

array([False, False, False,  True,  True])

In [66]:
x!=3

array([ True,  True, False,  True,  True])

In [68]:
x==3

array([False, False,  True, False, False])

In [70]:
(2*x)==(x**2)

array([False,  True, False, False, False])

In [75]:
np.count_nonzero(x<2)

1

In [95]:
np.sum(x<6)

11

In [97]:
np.any(x<5)

True

In [102]:
np.sum((x<1) & (x>0))

5

In [105]:
x=np.arange(0,10)
x[x<5]

array([0, 1, 2, 3, 4])

In [118]:
# fancy indexing
x=np.random.random((100,2))
index=np.random.randint(0,100,size=(10,))
x[index]
x[[1,2],1]

array([0.29257085, 0.58313798])

In [120]:
np.zeros_like?

In [131]:
t=np.dtype({"names":("name","age"),"formats":("U10","i4")})
data=np.zeros(4,dtype=t)
data
data[0]["name"]="Qianghui"
data[0]["age"]=28
data
data[0]
np.sum(data["age"]==28)
data[data["age"]==28]["name"]

array(['Qianghui'], dtype='<U10')

In [133]:
type1={"names":("name","age"),"formats":("U10","i4")}
np.dtype(type1)
type2={"names":("name","age"),"formats":("U10","i4")}

In [137]:
type3=np.dtype([("name",(np.str,10)),("age",np.int)])
np.ones(3,dtype=type3)

array([('1', 1), ('1', 1), ('1', 1)],
      dtype=[('name', '<U10'), ('age', '<i4')])

In [148]:
#sort
x=np.random.random(100)
x.sort()
x.reshape(50,2)

array([[9.12919541e-04, 6.06053344e-03],
       [1.40826893e-02, 2.13413833e-02],
       [4.05681139e-02, 4.37977641e-02],
       [4.42648554e-02, 5.72914796e-02],
       [7.00264476e-02, 8.16138880e-02],
       [8.41543120e-02, 8.83108220e-02],
       [9.93430721e-02, 1.00185111e-01],
       [1.24381331e-01, 1.27095348e-01],
       [1.28540834e-01, 1.34412531e-01],
       [1.40406847e-01, 1.46820325e-01],
       [1.64377011e-01, 1.91653135e-01],
       [2.10651624e-01, 2.20981034e-01],
       [2.42581772e-01, 2.52183267e-01],
       [2.73252296e-01, 2.78363393e-01],
       [2.89952643e-01, 2.96731808e-01],
       [3.10541719e-01, 3.14727799e-01],
       [3.21264734e-01, 3.35351729e-01],
       [3.36313961e-01, 3.39648347e-01],
       [3.57684351e-01, 3.63467152e-01],
       [3.64857313e-01, 3.92288617e-01],
       [3.96085209e-01, 4.10321506e-01],
       [4.16963454e-01, 4.39274974e-01],
       [4.40329956e-01, 4.58491162e-01],
       [4.67279406e-01, 5.07945846e-01],
       [5.108555